language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_script: npm run lockfile-update
script:
  - npm run test:prod && npm run build
after_script: npm run lockfile-upload
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
